const voiceButton=$('#voiceCaptureButton');if(voiceButton){voiceButton.textContent='🎙️ adicionar por áudio';voiceButton.classList.add('voice-entry');}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#authMessage');msg.textContent='Entrando…';msg.className='auth-message';const {data,error}=await db.auth.signInWithPassword({email:$('#authEmail').value.trim(),password:$('#authPassword').value});if(error){msg.textContent=error.message;msg.className='auth-message error';return;}msg.textContent='Login confirmado. Carregando sua campanha…';msg.className='auth-message success';if(data.session)await handleSession(data.session);});
$('#signUpButton').addEventListener('click',async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value,msg=$('#authMessage');if(!email||password.length<6){msg.textContent='Use um e-mail válido e uma senha com pelo menos 6 caracteres.';msg.className='auth-message error';return;}msg.textContent='Criando conta…';msg.className='auth-message';const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin,data:{display_name:'Edd'}}});if(error){msg.textContent=error.message;msg.className='auth-message error';return;}if(data.session){msg.textContent='Conta criada e login feito.';msg.className='auth-message success';await handleSession(data.session);}else{msg.textContent='Conta criada. Confirme o e-mail e depois volte para entrar.';msg.className='auth-message success';}});
$('#signOutButton').addEventListener('click',async()=>{await db.auth.signOut();await handleSession(null)});
$('#quickAdd').addEventListener('click',()=>openTaskModal());
$('#plannerAdd').addEventListener('click',()=>openTaskModal());
$('#inboxAdd').addEventListener('click',()=>openTaskModal(null,true));
$('#voiceCaptureButton').addEventListener('click',async()=>{try{if(typeof window.openVoiceCapture!=='function'){if(!window.__eddVoiceScript){window.__eddVoiceScript=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='audio.js?v=3';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}await window.__eddVoiceScript;}window.openVoiceCapture();}catch(error){console.error(error);showToast('Não consegui carregar a captura por áudio.','error');}});
$('#newRewardButton').addEventListener('click',()=>$('#rewardModal').hidden=false);
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();saveTask();});
$('#sendToInbox').addEventListener('click',()=>saveTask('inbox'));
$('#rewardForm').addEventListener('submit',e=>{e.preventDefault();saveReward();});
$('#taskProject').addEventListener('change',e=>{const p=projectById(e.target.value);if(p?.area_id)$('#taskArea').value=p.area_id;});

document.addEventListener('input',e=>{const scope=e.target.dataset.filterScope,key=e.target.dataset.filterKey;if(!scope||!key)return;state.filters[scope][key]=e.target.value;renderTaskBoards();});
document.addEventListener('change',async e=>{if(e.target.matches('.task-check')){const row=e.target.closest('[data-task-id]');if(row)await toggleTask(row.dataset.taskId,e.target.checked);return;}const scope=e.target.dataset.filterScope,key=e.target.dataset.filterKey;if(scope&&key){state.filters[scope][key]=e.target.value;renderTaskBoards();}});
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav){goView(nav.dataset.view);return;}const go=e.target.closest('[data-go-view]');if(go){goView(go.dataset.goView);return;}const close=e.target.closest('[data-close-modal]');if(close){closeModal(close.dataset.closeModal);return;}const edit=e.target.closest('[data-task-edit]');if(edit){openTaskModal(state.tasks.find(t=>t.id===edit.dataset.taskEdit));return;}const mood=e.target.closest('[data-mood]');if(mood){state.checkinMood=mood.dataset.mood;renderCheckin();return;}const energy=e.target.closest('[data-level]');if(energy&&energy.closest('#energySelector')){state.checkinEnergy=Number(energy.dataset.level);renderCheckin();return;}if(e.target.closest('#saveCheckin')){state.checkinNote=$('#checkinNote')?.value||'';await saveCheckin();return;}const select=e.target.closest('[data-select-quest]');if(select){await selectQuest(select.dataset.selectQuest);return;}const reroll=e.target.closest('[data-reroll-quest]');if(reroll){await rerollQuest(reroll.dataset.rerollQuest);return;}if(e.target.closest('#clearQuest')){await clearQuest();return;}const redeem=e.target.closest('[data-redeem]');if(redeem){await redeemReward(redeem.dataset.redeem);return;}const equip=e.target.closest('[data-equip-look]');if(equip){await equipCosmetic(equip.dataset.equipLook);return;}const project=e.target.closest('[data-project-jump]');if(project){goView('tasks');state.filters.planner.project=project.dataset.projectJump;renderFilters();renderTaskBoards();return;}});
$$('.modal-backdrop').forEach(backdrop=>backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.hidden=true;}));

init().catch(error=>{console.error(error);showToast(error.message||'Erro ao iniciar o app.','error');});