const DEFAULT_LOADOUT={shirt:'none',pants:'none',outerwear:'none',hat:'none',accessory:'none'};
let wardrobeCategory='shirt';
const CATEGORY_LABELS={shirt:'Camisas',pants:'Calças',outerwear:'Casacos & capas',hat:'Chapéus',accessory:'Acessórios'};
const AVATAR_CATALOG={
  shirt:[{code:'none',name:'Sem camisa extra'},{code:'tee_black',name:'Camiseta preta',index:0},{code:'shirt_white',name:'Camisa branca',index:1},{code:'hoodie_black',name:'Hoodie preto',index:2},{code:'overshirt_green',name:'Overshirt verde',index:3}],
  pants:[{code:'none',name:'Short base'},{code:'pants_black',name:'Calça escura',index:0},{code:'cargo_brown',name:'Cargo marrom',index:1},{code:'pants_crimson',name:'Calça carmesim',index:2},{code:'joggers_black',name:'Jogger preto',index:3}],
  outerwear:[{code:'none',name:'Sem casaco'},{code:'blazer_crimson',name:'Blazer carmesim',index:0},{code:'coat_noir',name:'Casaco noir',index:1},{code:'cape_green',name:'Capa verde',index:2},{code:'robe_scholar',name:'Capa scholar',index:3}],
  hat:[{code:'none',name:'Sem chapéu'},{code:'hat_explorer',name:'Chapéu explorer',index:0},{code:'cap_black',name:'Boné preto',index:1},{code:'beret_brown',name:'Boina marrom',index:2},{code:'wizard_hat',name:'Chapéu de mago',index:3}],
  accessory:[{code:'none',name:'Sem acessório'},{code:'glasses_round',name:'Óculos redondos',index:0},{code:'bag_crossbody',name:'Bolsa lateral',index:1},{code:'scarf_red',name:'Lenço vermelho',index:2},{code:'tool_belt',name:'Cinto de ferramentas',index:3}]
};
const AVATAR_FILES={base:'assets/avatar-base.b64',shirt:'assets/avatar-shirt.b64',pants:'assets/avatar-pants.b64',outerwear:'assets/avatar-outerwear.b64',hat:'assets/avatar-hat.b64',accessory:'assets/avatar-accessory.b64'};
let avatarAssets=null,avatarAssetsPromise=null;

(function injectModularAvatarStyles(){
 if(document.getElementById('edd-modular-avatar-styles'))return;
 const style=document.createElement('style');style.id='edd-modular-avatar-styles';style.textContent=`
 .outfit-tint{display:none!important}.avatar-sprite.modular-avatar{position:relative!important;aspect-ratio:160/249!important;display:block!important;height:auto!important;overflow:visible!important}.avatar-layer{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;pointer-events:none!important;image-rendering:pixelated!important}.avatar-base-layer{object-fit:contain!important;object-position:center bottom!important;z-index:1}.avatar-sprite-layer{background-repeat:no-repeat!important;background-size:200% 200%!important}.layer-pants{z-index:2}.layer-shirt{z-index:3}.layer-outerwear{z-index:4}.layer-hat{z-index:6}.layer-accessory{z-index:7}
 .wardrobe-grid{display:block!important}.wardrobe-builder{display:grid;grid-template-columns:minmax(260px,.78fr) minmax(0,1.5fr);gap:18px;align-items:stretch}.wardrobe-live{border:1px solid rgba(91,59,40,.14);border-radius:16px;background:radial-gradient(circle at 50% 22%,rgba(255,248,236,.95),rgba(229,214,194,.72) 52%,rgba(199,178,151,.34));padding:14px;display:flex;flex-direction:column;min-height:520px}.wardrobe-live-head{display:flex;justify-content:space-between;gap:10px}.wardrobe-live-head strong{font-size:16px}.wardrobe-live-head span{display:block;font-size:11px;color:var(--muted)}.wardrobe-live-stage{flex:1;min-height:390px;display:grid;place-items:center}.wardrobe-live-stage .avatar-sprite{width:min(250px,78%)}.wardrobe-loadout{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.wardrobe-loadout span{font-size:10px;border:1px solid rgba(91,59,40,.12);background:rgba(255,255,255,.46);border-radius:999px;padding:5px 8px}.wardrobe-reset{width:100%;margin-top:10px}.wardrobe-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.wardrobe-tab{border:1px solid rgba(91,59,40,.16);background:rgba(255,255,255,.35);color:var(--ink);border-radius:999px;padding:7px 11px;font-size:11px;font-weight:700;cursor:pointer}.wardrobe-tab.active{background:#3b2a21;color:#f6eadb;border-color:#3b2a21}.wardrobe-items{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.piece-card{border:1px solid rgba(91,59,40,.14);border-radius:14px;background:rgba(255,255,255,.38);padding:9px;display:grid;gap:8px;transition:.16s ease}.piece-card:hover{transform:translateY(-2px)}.piece-card.equipped{outline:2px solid rgba(118,139,111,.55);background:rgba(118,139,111,.10)}.piece-preview{height:170px;border:1px solid rgba(91,59,40,.10);border-radius:11px;background:radial-gradient(circle at 50% 28%,rgba(255,249,239,.92),rgba(226,211,191,.55));display:grid;place-items:center;position:relative;overflow:hidden}.piece-sprite{width:100%;height:100%;background-repeat:no-repeat;background-size:200% 200%;image-rendering:pixelated}.piece-none{font-size:38px;color:rgba(58,40,30,.35);font-weight:700}.piece-name{font-size:12px;font-weight:800}.piece-card .btn{width:100%;min-height:34px;font-size:11px;padding:6px 8px}.piece-status{position:absolute;left:7px;top:7px;font-size:9px;padding:4px 6px;border-radius:999px;background:rgba(45,33,26,.82);color:#f8eddd;z-index:2}.wardrobe-loading{padding:36px;text-align:center;color:var(--muted)}
 @media(max-width:1180px){.wardrobe-builder{grid-template-columns:1fr}.wardrobe-items{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:860px){.wardrobe-items{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.wardrobe-items{grid-template-columns:1fr}.piece-preview{height:150px}}
 `;document.head.appendChild(style);
})();

async function ensureAvatarAssets(){
 if(avatarAssets)return avatarAssets;
 if(!avatarAssetsPromise)avatarAssetsPromise=Promise.all(Object.entries(AVATAR_FILES).map(async([key,url])=>{const r=await fetch(`${url}?v=2`);if(!r.ok)throw new Error(`Falha ao carregar ${key}`);return [key,`data:image/webp;base64,${(await r.text()).trim()}`];})).then(entries=>avatarAssets=Object.fromEntries(entries)).catch(err=>{avatarAssetsPromise=null;console.error(err);showToast?.('Não consegui carregar o guarda-roupa.','error');throw err;});
 return avatarAssetsPromise;
}
function getAvatarLoadout(){return {...DEFAULT_LOADOUT,...(state.user?.user_metadata?.avatar_loadout||{})};}
function currentLookCode(){return getAvatarLoadout();}function currentLook(){return getAvatarLoadout();}
function categoryItems(c){return AVATAR_CATALOG[c]||[];}function itemMeta(c,code){return categoryItems(c).find(x=>x.code===code);}function itemName(c,code){return itemMeta(c,code)?.name||'Base';}
function spritePos(index=0){return [['0%','0%'],['100%','0%'],['0%','100%'],['100%','100%']][index]||['0%','0%'];}
function spriteStyle(category,index){const [x,y]=spritePos(index);return `background-image:url('${avatarAssets?.[category]||''}');background-position:${x} ${y};`;}
function avatarLayersMarkup(loadout=getAvatarLoadout()){
 let html=`<img class="avatar-layer avatar-base-layer" src="${avatarAssets.base}" alt="Edd em pixel art">`;
 for(const cat of ['pants','shirt','outerwear','hat','accessory']){const meta=itemMeta(cat,loadout[cat]);if(meta&&meta.code!=='none')html+=`<span class="avatar-layer avatar-sprite-layer layer-${cat}" style="${spriteStyle(cat,meta.index)}" aria-label="${escapeHtml(meta.name)}"></span>`;}
 return html;
}
function renderAvatarStack(wrap,loadout=getAvatarLoadout()){if(!wrap)return;if(!avatarAssets){wrap.innerHTML='<span class="wardrobe-loading">carregando…</span>';ensureAvatarAssets().then(()=>renderAvatarStack(wrap,loadout));return;}wrap.classList.add('modular-avatar');wrap.innerHTML=avatarLayersMarkup(loadout);}
function setAvatarSources(){const loadout=getAvatarLoadout();if(!avatarAssets){ensureAvatarAssets().then(setAvatarSources);return;}renderAvatarStack($('#homeAvatarWrap'),loadout);renderAvatarStack($('#sheetAvatarWrap'),loadout);}
function loadoutSummary(loadout){return Object.entries(loadout).filter(([,v])=>v&&v!=='none').map(([c,v])=>`<span>${escapeHtml(itemName(c,v))}</span>`).join('')||'<span>visual base</span>';}
function pieceCardMarkup(category,item,current){const equipped=current===item.code;return `<article class="piece-card ${equipped?'equipped':''}"><div class="piece-preview"><span class="piece-status">${equipped?'equipado':'disponível'}</span>${item.code==='none'?'<span class="piece-none">∅</span>':`<span class="piece-sprite" style="${spriteStyle(category,item.index)}"></span>`}</div><div class="piece-name">${escapeHtml(item.name)}</div><button class="btn ${equipped?'secondary':'primary'} small" data-equip-look="${category}:${item.code}">${equipped?'equipado':'equipar'}</button></article>`;}
function renderWardrobeItems(){const host=$('#wardrobeItems');if(!host||!avatarAssets)return;const loadout=getAvatarLoadout();host.innerHTML=categoryItems(wardrobeCategory).map(item=>pieceCardMarkup(wardrobeCategory,item,loadout[wardrobeCategory])).join('');}
function renderWardrobe(){const root=$('#wardrobeGrid');if(!root)return;if(!avatarAssets){root.innerHTML='<div class="wardrobe-loading">carregando guarda-roupa modular…</div>';ensureAvatarAssets().then(renderWardrobe);return;}const loadout=getAvatarLoadout(),count=Object.values(loadout).filter(v=>v&&v!=='none').length;$('#equippedLookLabel').textContent=`${count} peça${count===1?'':'s'} equipada${count===1?'':'s'}`;root.innerHTML=`<div class="wardrobe-builder"><section class="wardrobe-live"><div class="wardrobe-live-head"><div><strong>Seu Edd</strong><span>Monte o visual por camadas.</span></div><span>${count}/5 slots</span></div><div class="wardrobe-live-stage"><div class="avatar-sprite modular-avatar" id="wardrobeAvatar"></div></div><div class="wardrobe-loadout">${loadoutSummary(loadout)}</div><button class="btn secondary small wardrobe-reset" id="resetAvatarLoadout">voltar ao visual base</button></section><section class="wardrobe-catalog"><div class="wardrobe-tabs">${Object.entries(CATEGORY_LABELS).map(([k,l])=>`<button type="button" class="wardrobe-tab ${wardrobeCategory===k?'active':''}" data-wardrobe-category="${k}">${l}</button>`).join('')}</div><div class="wardrobe-items" id="wardrobeItems"></div></section></div>`;renderAvatarStack($('#wardrobeAvatar'),loadout);renderWardrobeItems();$$('.wardrobe-tab',root).forEach(btn=>btn.addEventListener('click',()=>{wardrobeCategory=btn.dataset.wardrobeCategory;renderWardrobe();}));$('#resetAvatarLoadout')?.addEventListener('click',()=>saveAvatarLoadout({...DEFAULT_LOADOUT},'Visual base restaurado.'));}
async function saveAvatarLoadout(next,message='Visual atualizado.'){const {data,error}=await db.auth.updateUser({data:{avatar_loadout:next}});if(error)return showToast(error.message,'error');if(data?.user)state.user=data.user;setAvatarSources();renderWardrobe();showToast(message,'success');}
async function equipCosmetic(encoded){const [category,code]=String(encoded||'').split(':');if(!CATEGORY_LABELS[category]||!categoryItems(category).some(x=>x.code===code))return;const next={...getAvatarLoadout(),[category]:code};await saveAvatarLoadout(next,code==='none'?`${CATEGORY_LABELS[category]} removido.`:`${itemName(category,code)} equipado.`);}